---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[convergence_handler]
      - recipe[convergence_handler_test::file]
    attributes:

  - name: filters
    run_list:
      - recipe[convergence_handler_test::filters]
      - recipe[convergence_handler_test::file]
    attributes:
