sudo: required
dist: trusty

services:
  -docker

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

env:
  matrix:
    - INSTANCE=default-ubuntu-1204
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-centos-66

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - make test

after_script:
  - bundle exec kitchen destroy all

